import type { Metadata } from 'next'
import { Fira_Sans, Fira_Mono } from 'next/font/google'
import './globals.css'
import { Toaster } from 'sonner'

const firaSans = Fira_Sans({
    weight: ['400', '500', '700'],
    subsets: ['latin'],
    variable: '--font-sans',
})

const firaMono = Fira_Mono({
    weight: ['400', '700'],
    subsets: ['latin'],
    variable: '--font-mono',
})

export const metadata: Metadata = {
    title: 'Controle Financeiro de Frete',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="pt-br" className="light">
            <body className={`${firaSans.variable} ${firaMono.variable} antialiased overflow-hidden`}>
                {children} <Toaster expand={true} />
            </body>
        </html>
    )
}
